// <auto-generated />
using System;
using GYM_Manage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GYM_Manage.Migrations
{
    [DbContext(typeof(GYM_DBcontext))]
    [Migration("20250330031920_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GYM_Manage.Models.BaiViet", b =>
                {
                    b.Property<int>("MaBaiViet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaiViet"));

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(555)
                        .HasColumnType("nvarchar(555)");

                    b.Property<int>("IDNguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("MoTaNgan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBaiViet");

                    b.HasIndex("IDNguoiTao");

                    b.ToTable("BaiViets");
                });

            modelBuilder.Entity("GYM_Manage.Models.DangKyGoiTap", b =>
                {
                    b.Property<int>("MaDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDangKy"));

                    b.Property<int>("MaGoiTap")
                        .HasColumnType("int");

                    b.Property<int>("MaThanhVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDangKy");

                    b.HasIndex("MaGoiTap");

                    b.HasIndex("MaThanhVien");

                    b.ToTable("DangKyGoiTaps");
                });

            modelBuilder.Entity("GYM_Manage.Models.GoiTap", b =>
                {
                    b.Property<int>("MaGoiTap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGoiTap"));

                    b.Property<string>("AnhDemo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenGoiTap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThoiHan")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaGoiTap");

                    b.ToTable("GoiTaps");
                });

            modelBuilder.Entity("GYM_Manage.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<int>("MaThanhToan")
                        .HasColumnType("int");

                    b.Property<int>("MaThanhVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayHoaDon")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongSoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaThanhToan");

                    b.HasIndex("MaThanhVien");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("GYM_Manage.Models.HuanLuyenVien", b =>
                {
                    b.Property<int>("MaHuanLuyenVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHuanLuyenVien"));

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChungChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuyenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTuyenDung")
                        .HasColumnType("datetime2");

                    b.HasKey("MaHuanLuyenVien");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("HuanLuyenViens");
                });

            modelBuilder.Entity("GYM_Manage.Models.LichTap", b =>
                {
                    b.Property<int>("MaLichTap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichTap"));

                    b.Property<int>("MaHuanLuyenVien")
                        .HasColumnType("int");

                    b.Property<int>("MaThanhVien")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLichTap");

                    b.HasIndex("MaHuanLuyenVien");

                    b.HasIndex("MaThanhVien");

                    b.ToTable("LichTaps");
                });

            modelBuilder.Entity("GYM_Manage.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("GYM_Manage.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<int>("MaDangKyGoiTap")
                        .HasColumnType("int");

                    b.Property<int>("MaThanhVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ThanhVienMaThanhVien")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaDangKyGoiTap");

                    b.HasIndex("MaThanhVien");

                    b.HasIndex("ThanhVienMaThanhVien");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("GYM_Manage.Models.ThanhVien", b =>
                {
                    b.Property<int>("MaThanhVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhVien"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaThanhVien");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("SoDienThoai")
                        .IsUnique();

                    b.ToTable("ThanhViens");
                });

            modelBuilder.Entity("GYM_Manage.Models.ThietBi", b =>
                {
                    b.Property<int>("MaThietBi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThietBi"));

                    b.Property<string>("DanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBaoTriCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayMua")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenThietBi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaThietBi");

                    b.ToTable("ThietBis");
                });

            modelBuilder.Entity("GYM_Manage.Models.BaiViet", b =>
                {
                    b.HasOne("GYM_Manage.Models.NguoiDung", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("IDNguoiTao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("GYM_Manage.Models.DangKyGoiTap", b =>
                {
                    b.HasOne("GYM_Manage.Models.GoiTap", "GoiTap")
                        .WithMany()
                        .HasForeignKey("MaGoiTap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GYM_Manage.Models.ThanhVien", "ThanhVien")
                        .WithMany()
                        .HasForeignKey("MaThanhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoiTap");

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("GYM_Manage.Models.HoaDon", b =>
                {
                    b.HasOne("GYM_Manage.Models.ThanhToan", "ThanhToan")
                        .WithMany()
                        .HasForeignKey("MaThanhToan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GYM_Manage.Models.ThanhVien", "ThanhVien")
                        .WithMany()
                        .HasForeignKey("MaThanhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThanhToan");

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("GYM_Manage.Models.HuanLuyenVien", b =>
                {
                    b.HasOne("GYM_Manage.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GYM_Manage.Models.LichTap", b =>
                {
                    b.HasOne("GYM_Manage.Models.HuanLuyenVien", "HuanLuyenVien")
                        .WithMany()
                        .HasForeignKey("MaHuanLuyenVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GYM_Manage.Models.ThanhVien", "ThanhVien")
                        .WithMany()
                        .HasForeignKey("MaThanhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HuanLuyenVien");

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("GYM_Manage.Models.ThanhToan", b =>
                {
                    b.HasOne("GYM_Manage.Models.DangKyGoiTap", "DangKyGoiTap")
                        .WithMany()
                        .HasForeignKey("MaDangKyGoiTap")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GYM_Manage.Models.ThanhVien", "ThanhVien")
                        .WithMany()
                        .HasForeignKey("MaThanhVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GYM_Manage.Models.ThanhVien", null)
                        .WithMany("ThanhToans")
                        .HasForeignKey("ThanhVienMaThanhVien");

                    b.Navigation("DangKyGoiTap");

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("GYM_Manage.Models.ThanhVien", b =>
                {
                    b.HasOne("GYM_Manage.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GYM_Manage.Models.ThanhVien", b =>
                {
                    b.Navigation("ThanhToans");
                });
#pragma warning restore 612, 618
        }
    }
}
